# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrApp', '0002_auto_20170127_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=45),
        ),
    ]
