# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='friendship',
            name='p1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='p1', to='friendOnFriends.User'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='p2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='p2', to='friendOnFriends.User'),
        ),
    ]
